name: actions pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}

    - name: Clone manifests repository
      uses: actions/checkout@v3
      with:
        repository: your-username/hello-manifests
        path: manifests
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Update image tag in deployment manifest
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}|g" manifests/deployment.yaml

    - name: Commit and push updated manifests
      run: |
        cd manifests
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push origin main
